### ISSUE TITLE
Installation av Vivado batch mode

### ISSUE THREAD

**Issue by SimonHotDog** [KusinVitamin/Projekt-Hemsida#2]
Installation av Vivado via batch, utan grafiskt gränssnitt

**Comment by Rickos99** [comment]
A document draft of the installation of Vivado can be found at [docs/Xilinx, Install Vivado.md](https://github.com/KusinVitamin/Projekt-Hemsida/blob/main/docs/Xilinx%2C%20Install%20Vivado.md).
